version: "3.8"
networks:
  react_express:
    driver: bridge
services:
  front:
    build: 
      context: .
    container_name: node
    volumes:
      - ./app:/app
    working_dir: /app
    dns:
      - 8.8.8.8
      - 9.9.9.9
    ports:
      - 3000:3000
      - 9005:9005
      # - 6006:6006      
    tty: true
    stdin_open: true
    environment:
      - CHOKIDAR_USEPOLLING=true
    command: 
      sh -c 'npm start'
  storybook:
    build:
      context: .
      dockerfile: Dockerfile
    command: "npm run storybook:docker"
    ports:
      - "6006:6006"
    volumes:
      - ./app:/app
    networks:
      - react_express
    # environment:
    #   - NODE_ENV=development
  server:  # Express用のコンテナ
    build: ./server
    container_name: server
    tty: true
    volumes:
      - ./server:/server
    working_dir: "/server"
    ports:
      - 3002:3000
    command: npm run dev
    networks:
      - react_express
  mysqldb:
    image: mysql:8.0
    container_name: mysqldb
    # env_file:
    #   - ".env"
    volumes:
      - db-store:/var/lib/mysql
      - ./database/logs:/var/log/mysql
      - ./database/my.cnf:/etc/mysql/conf.d/my.cnf
    environment:
      MYSQL_DATABASE: 'db'
      # MYSQL_USER: '${DB_USERNAME}'
      # MYSQL_PASSWORD: '${DB_PASSWORD}'
      # MYSQL_ROOT_USER: root
      # MYSQL_ROOT_PASSWORD: '${ROOT_PASSWORD}'
      MYSQL_ROOT_PASSWORD: password
      # MYSQL_ROOT_HOST: '%'
      TZ: '${TZ}'
    ports:
      - ${DB_PORT}:3306 # 公開ポート番号:3306(デフォルト値）
    restart: always
    command: --default-authentication-plugin=mysql_native_password --sort_buffer_size=1073741824
    networks:
      - react_express   
    # command: mysqld --character-set-server=utf8 --collation-server=utf8_unicode_ci
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    restart: always
    # env_file:
    #   - ".env"
    depends_on:
      - mysqldb
    environment:
      - PMA_ARBITRARY=1
      - PMA_HOSTS=mysql_host
      # - PMA_HOST=${DB_HOST}
      # - PMA_USER=${DB_USERNAME}
      # - PMA_PASSWORD=${DB_PASSW\ORD}
      # - MYSQL_USER=${DB_USERNAME}
      # - MYSQL_PASSWORD=${DB_PASSWORD}
      # - MYSQL_ROOT_PASSWORD=${ROOT_PASSWORD}
    ports:
      - "8001:80"
    volumes:
      - ./phpmyadmin/sessions:/sessions
    networks:
      - react_express
volumes:
  db-store: