version: "3.8"
services:
  front:
    build: 
      context: .
    container_name: node
    volumes:
      - ./app:/app
    working_dir: /app
    ports:
      - 3000:3000
      # - 6006:6006      
    tty: true
    stdin_open: true
    environment:
      - CHOKIDAR_USEPOLLING=true
    command: 
      sh -c 'npm start'
  storybook:
    build:
      context: .
      dockerfile: Dockerfile
    command: "npm run storybook:docker"
    ports:
      - "6006:6006"
    volumes:
      - ./app:/app
    # environment:
    #   - NODE_ENV=development